Submitted By: Samujwal Shrestha

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [1]:
import numpy as np
import time

Problem - 1: Array Creation:

In [2]:
# 1) Empty 2x2 array
empty_2x2 = np.empty((2, 2))
print("1) Empty 2x2:\n", empty_2x2)

# 2) All ones array 4x2
ones_4x2 = np.ones((4, 2))
print("\n2) Ones 4x2:\n", ones_4x2)

# 3) Array filled with a value
filled = np.full((3, 4), 7)  # example shape 3x4, fill with 7
print("\n3) Filled array (3x4) with 7:\n", filled)

# 4) Zeros array same shape as a given array
given = np.array([[1.5, 2.5], [3.5, 4.5]])
zeros_like_given = np.zeros_like(given)
print("\n4) Zeros like given:\n", zeros_like_given)

# 5) Ones array same shape as a given array
ones_like_given = np.ones_like(given)
print("\n5) Ones like given:\n", ones_like_given)

# 6) Convert list to numpy array
new_list = [1, 2, 3, 4]
converted = np.array(new_list)
print("\n6) Converted list to np array:\n", converted)

1) Empty 2x2:
 [[2.35880818e-315 0.00000000e+000]
 [4.94065646e-324 6.52151963e-310]]

2) Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3) Filled array (3x4) with 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

4) Zeros like given:
 [[0. 0.]
 [0. 0.]]

5) Ones like given:
 [[1. 1.]
 [1. 1.]]

6) Converted list to np array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1) Array from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1) Array 10–49:\n", arr_10_49)

# 2) 3x3 matrix 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2) 3x3 matrix 0–8:\n", matrix_3x3)

# 3) Identity matrix 3x3
I3 = np.eye(3)
print("\n3) Identity 3x3:\n", I3)

# 4) Random array of size 30 + mean
r30 = np.random.random(30)
print("\n4) Random 30 array:\n", r30)
print("Mean:", r30.mean())

# 5) 10x10 random array min, max
r10 = np.random.random((10, 10))
print("\n5) Random 10x10:\n", r10)
print("Min:", r10.min(), "Max:", r10.max())

# 6) Zero array size 10, replace 5th element with 1
z10 = np.zeros(10)
z10[4] = 1
print("\n6) Replace 5th with 1:\n", z10)

# 7) Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
rev = arr[::-1]
print("\n7) Reversed array:\n", rev)

# 8) Border 1s, inside 0s (example 5x5)
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8) Border ones, inside zeros:\n", border)

# 9) 8x8 checkerboard
chk = np.zeros((8, 8), dtype=int)
chk[1::2, ::2] = 1
chk[::2, 1::2] = 1
print("\n9) Checkerboard pattern:\n", chk)

1) Array 10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2) 3x3 matrix 0–8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3) Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4) Random 30 array:
 [0.89745529 0.4149196  0.17346735 0.72514082 0.68102589 0.97232506
 0.94305274 0.87983303 0.51683927 0.20106211 0.23903925 0.92530992
 0.92531403 0.5338704  0.70831029 0.38832965 0.57218385 0.44021295
 0.44327282 0.20109001 0.7314028  0.51744375 0.64917909 0.89441897
 0.88320365 0.91334356 0.48680441 0.7824714  0.36943942 0.07857862]
Mean: 0.602944666450695

5) Random 10x10:
 [[0.18927893 0.2403392  0.98553289 0.80289242 0.40264448 0.41391366
  0.20599756 0.07201749 0.42504634 0.9754853 ]
 [0.54773953 0.59668168 0.47509423 0.86837044 0.76173119 0.9500013
  0.03662115 0.74967267 0.07598577 0.73532886]
 [0.50281625 0.98062373 0.25649916 0.45862832 0.08672286 0.26939635
  0.88490724 0.39858494 0.91158268 0.26083051]
 [0.074129

Problem - 3: Array Operations:

In [4]:
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1) Add
print("1) x + y:\n", x + y)

# 2) Subtract
print("\n2) x - y:\n", x - y)

# 3) Multiply with integers
print("\n3) x * 3:\n", x * 3)
print("y * 2:\n", y * 2)

# 4) Square elements
print("\n4) x squared:\n", x ** 2)

# 5) Dot products
print("\n5a) v·w =", np.dot(v, w))
print("5b) x·v:\n", x.dot(v))
print("5c) x·y:\n", x.dot(y))

# 6) Concatenate
xy_concat = np.concatenate((x, y), axis=0)
print("\n6a) x & y row concat:\n", xy_concat)

vw_concat = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\n6b) v & w column concat:\n", vw_concat)

# 7) Try concatenating x and v
try:
    bad = np.concatenate((x, v))
except Exception as e:
    print("\n7) Error concatenating x and v:\n", e)
    print("Reason: x is 2D with shape", x.shape,
          "but v is 1D with shape", v.shape)


1) x + y:
 [[ 6  8]
 [10 13]]

2) x - y:
 [[-4 -4]
 [-4 -3]]

3) x * 3:
 [[ 3  6]
 [ 9 15]]
y * 2:
 [[10 12]
 [14 16]]

4) x squared:
 [[ 1  4]
 [ 9 25]]

5a) v·w = 219
5b) x·v:
 [29 77]
5c) x·y:
 [[19 22]
 [50 58]]

6a) x & y row concat:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b) v & w column concat:
 [[ 9 11]
 [10 12]]

7) Error concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D with shape (2, 2) but v is 1D with shape (2,)


Problem - 4: Matrix Operations:

In [5]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1) A * A^-1 = I
A_inv = np.linalg.inv(A)
print("1) A @ A_inv:\n", A @ A_inv)

# 2) AB != BA
print("\n2) AB:\n", A @ B)
print("BA:\n", B @ A)
print("Equal?", np.allclose(A @ B, B @ A))

# 3) (AB)^T = B^T A^T
left = (A @ B).T
right = B.T @ A.T
print("\n3) (AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Equal?", np.allclose(left, right))

1) A @ A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2) AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Equal? False

3) (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Equal? True


 Linear equation using Inverse Methods

In [6]:
A_sys = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B_sys = np.array([-1, -3, 9])

# Using inverse
X_inv = np.linalg.inv(A_sys) @ B_sys
print("Solution using inverse:\n", X_inv)

# Using solve()
X_solve = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:\n", X_solve)

Solution using inverse:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?

Experiment: Python Lists vs NumPy Speed

In [7]:
N = 1_000_000

# Prepare lists and numpy arrays
list1 = list(range(N))
list2 = list(range(N))

arr1 = np.array(list1)
arr2 = np.array(list2)

# 1) Element-wise addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(N)]
print("List addition time:", time.time() - start)

start = time.time()
np_add = arr1 + arr2
print("NumPy addition time:", time.time() - start)

# 2) Element-wise multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(N)]
print("\nList multiplication time:", time.time() - start)

start = time.time()
np_mul = arr1 * arr2
print("NumPy multiplication time:", time.time() - start)

# 3) Dot product
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(N))
print("\nList dot product time:", time.time() - start)

start = time.time()
np_dot = np.dot(arr1, arr2)
print("NumPy dot product time:", time.time() - start)

List addition time: 0.11452007293701172
NumPy addition time: 0.005655050277709961

List multiplication time: 0.11749935150146484
NumPy multiplication time: 0.005918979644775391

List dot product time: 0.11600351333618164
NumPy dot product time: 0.001988649368286133


Matrix Multiplication Test (1000×1000)

In [9]:
size = 1000

# Python list matrices
M1_list = [[1]*size for _ in range(size)]
M2_list = [[1]*size for _ in range(size)]

# NumPy matrices
M1_np = np.ones((size, size))
M2_np = np.ones((size, size))

# Python list matrix multiplication
start = time.time()
M_res_list = [[sum(M1_list[i][k] * M2_list[k][j] for k in range(size))
               for j in range(size)]
              for i in range(size)]
print("List matrix multiplication time:", time.time() - start)

# NumPy matrix multiplication
start = time.time()
M_res_np = M1_np @ M2_np
print("NumPy matrix multiplication time:", time.time() - start)

List matrix multiplication time: 119.09069347381592
NumPy matrix multiplication time: 0.07277202606201172
